"""share: recipient_id + redeemed_at (trwaly dostep)

Revision ID: 0a36b5ad5c7e
Revises: e8a3c1f6b240
Create Date: 2026-06-15 19:43:46.768505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0a36b5ad5c7e'
down_revision: Union[str, None] = 'e8a3c1f6b240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_share', sa.Column('recipient_id', sa.Uuid(), nullable=True))
    op.add_column('document_share', sa.Column('redeemed_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'document_share', 'app_user', ['recipient_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_share', type_='foreignkey')
    op.drop_column('document_share', 'redeemed_at')
    op.drop_column('document_share', 'recipient_id')
    # ### end Alembic commands ###
