"""pakiet rozszerzen: rodzina, watch terminow, slowniki

Revision ID: 151470653fdf
Revises: 3d4933af1695
Create Date: 2026-06-11 01:07:01.110592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '151470653fdf'
down_revision: Union[str, None] = '3d4933af1695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('icd10_dict',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('medication_dict',
    sa.Column('med_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('form', sa.String(length=100), nullable=True),
    sa.Column('strength', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('med_id')
    )
    # server_default — tabele mają już wiersze
    op.add_column('appointment', sa.Column('notify_earlier', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('clinic', sa.Column('earlier_notice_min_hours', sa.Integer(), nullable=False, server_default='24'))
    op.add_column('patient', sa.Column('guardian_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_patient_guardian', 'patient', 'app_user', ['guardian_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_patient_guardian', 'patient', type_='foreignkey')
    op.drop_column('patient', 'guardian_id')
    op.drop_column('clinic', 'earlier_notice_min_hours')
    op.drop_column('appointment', 'notify_earlier')
    op.drop_table('medication_dict')
    op.drop_table('icd10_dict')
    # ### end Alembic commands ###
