"""appointment: confirmation_token (potwierdzanie z linka SMS)

Revision ID: 37e6c795b09c
Revises: f055fc83c372
Create Date: 2026-06-16 01:05:17.211731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '37e6c795b09c'
down_revision: Union[str, None] = 'f055fc83c372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('confirmation_token', sa.String(length=43), nullable=True))
    op.create_unique_constraint(None, 'appointment', ['confirmation_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointment', type_='unique')
    op.drop_column('appointment', 'confirmation_token')
    # ### end Alembic commands ###
