"""indeksy wydajnosciowe na hot-sciezkach

Revision ID: 3c462e2f3f4f
Revises: f2b593804756
Create Date: 2026-06-23 09:28:34.090058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3c462e2f3f4f'
down_revision: Union[str, None] = 'f2b593804756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_appointment_clinic_id'), 'appointment', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_appointment_doctor_id'), 'appointment', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointment_patient_id'), 'appointment', ['patient_id'], unique=False)
    op.create_index('ix_appointment_status_dt', 'appointment', ['appointment_status', 'appointment_datetime'], unique=False)
    op.create_index(op.f('ix_clinical_note_patient_id'), 'clinical_note', ['patient_id'], unique=False)
    op.create_index(op.f('ix_medical_document_doctor_id'), 'medical_document', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_medical_document_patient_id'), 'medical_document', ['patient_id'], unique=False)
    op.create_index('ix_notification_user_read', 'notification', ['user_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_payment_appointment_id'), 'payment', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_review_doctor_id'), 'review', ['doctor_id'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_doctor_id'), table_name='review')
    op.drop_index(op.f('ix_payment_appointment_id'), table_name='payment')
    op.drop_index('ix_notification_user_read', table_name='notification')
    op.drop_index(op.f('ix_medical_document_patient_id'), table_name='medical_document')
    op.drop_index(op.f('ix_medical_document_doctor_id'), table_name='medical_document')
    op.drop_index(op.f('ix_clinical_note_patient_id'), table_name='clinical_note')
    op.drop_index('ix_appointment_status_dt', table_name='appointment')
    op.drop_index(op.f('ix_appointment_patient_id'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_doctor_id'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_clinic_id'), table_name='appointment')
    # ### end Alembic commands ###
