"""udostepnianie kodem + przypomnienia

Revision ID: 3d4933af1695
Revises: d09bd80266aa
Create Date: 2026-06-10 21:48:14.800455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3d4933af1695'
down_revision: Union[str, None] = 'd09bd80266aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_share',
    sa.Column('share_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('access_code', sa.String(length=10), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('share_id'),
    sa.UniqueConstraint('access_code')
    )
    # server_default: tabela appointment ma już wiersze — NOT NULL wymaga wartości
    op.add_column('appointment', sa.Column('reminder_sent', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment', 'reminder_sent')
    op.drop_table('document_share')
    # ### end Alembic commands ###
