"""medical_document: appointment_id i doctor_id nullable (wyniki z papieru)

Revision ID: 4b0f1a7bf3a1
Revises: 8cedd4f538f3
Create Date: 2026-06-15 22:55:54.418755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4b0f1a7bf3a1'
down_revision: Union[str, None] = '8cedd4f538f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medical_document', 'appointment_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('medical_document', 'doctor_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medical_document', 'doctor_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('medical_document', 'appointment_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
