"""certificate (zaswiadczenie lekarskie)

Revision ID: 58fe35445245
Revises: adf009d6f92f
Create Date: 2026-06-15 02:28:03.115343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '58fe35445245'
down_revision: Union[str, None] = 'adf009d6f92f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate',
    sa.Column('certificate_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('certificate_code', sa.String(length=50), nullable=False),
    sa.Column('purpose', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['medical_document.document_id'], ),
    sa.PrimaryKeyConstraint('certificate_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certificate')
    # ### end Alembic commands ###
