"""push_token: tokeny push urzadzen pacjenta

Revision ID: 5958ff9dcb7e
Revises: f2a3b4c5d6e7
Create Date: 2026-06-23 07:50:48.918219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5958ff9dcb7e'
down_revision: Union[str, None] = 'f2a3b4c5d6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_token',
    sa.Column('push_token_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=256), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('push_token_id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('ix_push_token_user', 'push_token', ['user_id'])


def downgrade() -> None:
    op.drop_index('ix_push_token_user', table_name='push_token')
    op.drop_table('push_token')
