"""audit_log (RODO)

Revision ID: 7bb1770223eb
Revises: 58fe35445245
Create Date: 2026-06-15 03:47:30.498585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7bb1770223eb'
down_revision: Union[str, None] = '58fe35445245'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('log_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_role', sa.String(length=30), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=True),
    sa.Column('detail', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['app_user.user_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_log')
    # ### end Alembic commands ###
