"""supabase auth: supabase_uid, hashed_password nullable

Revision ID: 8036bf49a3e3
Revises: 49b247296e47
Create Date: 2026-06-10 04:22:04.007829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8036bf49a3e3'
down_revision: Union[str, None] = '49b247296e47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('supabase_uid', sa.Uuid(), nullable=False))
    op.alter_column('app_user', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_unique_constraint(None, 'app_user', ['supabase_uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'app_user', type_='unique')
    op.alter_column('app_user', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('app_user', 'supabase_uid')
    # ### end Alembic commands ###
