"""appointment: allow_online (tryb stacjonarny z opcja teleporady)

Revision ID: 8cedd4f538f3
Revises: e13168fbde53
Create Date: 2026-06-15 22:27:13.424961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8cedd4f538f3'
down_revision: Union[str, None] = 'e13168fbde53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('allow_online', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment', 'allow_online')
    # ### end Alembic commands ###
