"""schemat poczatkowy (UUID)

Revision ID: 934810a5ab0a
Revises: 
Create Date: 2026-06-12 13:43:44.540536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '934810a5ab0a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinic',
    sa.Column('clinic_id', sa.Uuid(), nullable=False),
    sa.Column('clinic_name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=60), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('clinic_email', sa.String(length=100), nullable=True),
    sa.Column('earlier_notice_min_hours', sa.Integer(), nullable=False),
    sa.Column('slot_interval_min', sa.Integer(), nullable=False),
    sa.Column('confirmation_required', sa.Boolean(), nullable=False),
    sa.Column('confirmation_hours', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('clinic_id')
    )
    op.create_table('icd10_dict',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('medication_dict',
    sa.Column('med_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('form', sa.String(length=100), nullable=True),
    sa.Column('strength', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('med_id')
    )
    op.create_table('role',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('role_description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('app_user',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('supabase_uid', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('active_account', sa.Boolean(), nullable=False),
    sa.Column('notify_sms', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('supabase_uid')
    )
    op.create_table('administrator',
    sa.Column('administrator_id', sa.Uuid(), nullable=False),
    sa.Column('is_system_admin', sa.Boolean(), nullable=False),
    sa.Column('is_clinic_admin', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['administrator_id'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('administrator_id')
    )
    op.create_table('doctor',
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=False),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.Column('academic_title', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('doctor_id')
    )
    op.create_table('notification',
    sa.Column('notification_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('notification_title', sa.String(length=100), nullable=False),
    sa.Column('notification_content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('nurse',
    sa.Column('nurse_id', sa.Uuid(), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=False),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['nurse_id'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('nurse_id')
    )
    op.create_table('patient',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('pesel', sa.String(length=11), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('insurance_status', sa.Boolean(), nullable=False),
    sa.Column('guardian_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['guardian_id'], ['app_user.user_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_table('staff_clinic',
    sa.Column('staff_clinic_id', sa.Uuid(), nullable=False),
    sa.Column('clinic_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.clinic_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('staff_clinic_id')
    )
    op.create_table('appointment',
    sa.Column('appointment_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=True),
    sa.Column('doctor_id', sa.Uuid(), nullable=True),
    sa.Column('nurse_id', sa.Uuid(), nullable=True),
    sa.Column('clinic_id', sa.Uuid(), nullable=False),
    sa.Column('appointment_datetime', sa.DateTime(), nullable=False),
    sa.Column('appointment_status', sa.String(length=50), nullable=False),
    sa.Column('appointment_type', sa.String(length=50), nullable=False),
    sa.Column('appointment_notes', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), nullable=False),
    sa.Column('notify_earlier', sa.Boolean(), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=True),
    sa.Column('referral_required', sa.Boolean(), nullable=False),
    sa.Column('referral_document_id', sa.Uuid(), nullable=True),
    sa.Column('external_referral', sa.Boolean(), nullable=False),
    sa.Column('confirmation_requested', sa.Boolean(), nullable=False),
    sa.Column('patient_confirmed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.clinic_id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.doctor_id'], ),
    sa.ForeignKeyConstraint(['nurse_id'], ['nurse.nurse_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.create_table('document_share',
    sa.Column('share_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('access_code', sa.String(length=10), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('share_id'),
    sa.UniqueConstraint('access_code')
    )
    op.create_table('patient_clinic',
    sa.Column('patient_clinic_id', sa.Uuid(), nullable=False),
    sa.Column('clinic_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.clinic_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('patient_clinic_id')
    )
    op.create_table('waiting_list',
    sa.Column('entry_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('specialization', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('entry_id')
    )
    op.create_table('medical_document',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('appointment_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('document_content', sa.Text(), nullable=True),
    sa.Column('document_status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.appointment_id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.doctor_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('payment',
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('appointment_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('provider_ref', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.appointment_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_table('review',
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('appointment_id', sa.Uuid(), nullable=True),
    sa.Column('doctor_id', sa.Uuid(), nullable=True),
    sa.Column('clinic_id', sa.Uuid(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.appointment_id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.clinic_id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.doctor_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_table('lab_result',
    sa.Column('lab_result_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('test_type', sa.String(length=100), nullable=False),
    sa.Column('test_description', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['medical_document.document_id'], ),
    sa.PrimaryKeyConstraint('lab_result_id')
    )
    op.create_table('prescription',
    sa.Column('prescription_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('prescription_code', sa.String(length=50), nullable=False),
    sa.Column('prescribed_drugs', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['medical_document.document_id'], ),
    sa.PrimaryKeyConstraint('prescription_id')
    )
    op.create_table('referral',
    sa.Column('referral_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('referral_code', sa.String(length=50), nullable=False),
    sa.Column('referral_type', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['medical_document.document_id'], ),
    sa.PrimaryKeyConstraint('referral_id')
    )
    op.create_table('sick_leave',
    sa.Column('sick_leave_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('sick_leave_code', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('sent_to_zus', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['medical_document.document_id'], ),
    sa.PrimaryKeyConstraint('sick_leave_id')
    )
    op.create_table('nursing_procedure',
    sa.Column('procedure_id', sa.Uuid(), nullable=False),
    sa.Column('nurse_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('clinic_id', sa.Uuid(), nullable=False),
    sa.Column('appointment_id', sa.Uuid(), nullable=False),
    sa.Column('referral_id', sa.Uuid(), nullable=False),
    sa.Column('procedure_type', sa.String(length=100), nullable=False),
    sa.Column('procedure_status', sa.String(length=50), nullable=False),
    sa.Column('procedure_datetime', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.appointment_id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.clinic_id'], ),
    sa.ForeignKeyConstraint(['nurse_id'], ['nurse.nurse_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.ForeignKeyConstraint(['referral_id'], ['referral.referral_id'], ),
    sa.PrimaryKeyConstraint('procedure_id')
    )
    # ### end Alembic commands ###

    # FK domykający cykl appointment <-> medical_document (use_alter)
    op.create_foreign_key(
        "fk_appointment_referral_doc", "appointment", "medical_document",
        ["referral_document_id"], ["document_id"],
    )

    # seed słownika ról (dawna migracja a1b2c3d4e5f6, teraz z UUID)
    import uuid

    role = sa.table(
        "role",
        sa.column("role_id", sa.Uuid),
        sa.column("role_name", sa.String),
        sa.column("role_description", sa.String),
    )
    op.bulk_insert(role, [
        {"role_id": uuid.uuid4(), "role_name": n, "role_description": d}
        for n, d in [
            ("pacjent", "Pacjent — Portal Pacjenta i aplikacja mobilna"),
            ("lekarz", "Lekarz — Portal Lekarza"),
            ("pielegniarka", "Pielęgniarka — Portal Pielęgniarki"),
            ("rejestracja", "Pracownik rejestracji — Panel Poradni"),
            ("kierownik", "Kierownik placówki — Panel Poradni"),
            ("administrator", "Administrator systemowy — Panel Administratora"),
        ]
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nursing_procedure')
    op.drop_table('sick_leave')
    op.drop_table('referral')
    op.drop_table('prescription')
    op.drop_table('lab_result')
    op.drop_table('review')
    op.drop_table('payment')
    op.drop_table('medical_document')
    op.drop_table('waiting_list')
    op.drop_table('patient_clinic')
    op.drop_table('document_share')
    op.drop_table('appointment')
    op.drop_table('staff_clinic')
    op.drop_table('patient')
    op.drop_table('nurse')
    op.drop_table('notification')
    op.drop_table('doctor')
    op.drop_table('administrator')
    op.drop_table('app_user')
    op.drop_table('role')
    op.drop_table('medication_dict')
    op.drop_table('icd10_dict')
    op.drop_table('clinic')
    # ### end Alembic commands ###
