"""clinical_note (nota z wizyty + addenda + audyt)

Revision ID: adf009d6f92f
Revises: d401b2a06849
Create Date: 2026-06-15 01:55:38.503521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'adf009d6f92f'
down_revision: Union[str, None] = 'd401b2a06849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_note',
    sa.Column('note_id', sa.Uuid(), nullable=False),
    sa.Column('appointment_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('signed_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.appointment_id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['doctor.doctor_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.ForeignKeyConstraint(['signed_by'], ['doctor.doctor_id'], ),
    sa.PrimaryKeyConstraint('note_id'),
    sa.UniqueConstraint('appointment_id')
    )
    op.create_table('note_addendum',
    sa.Column('addendum_id', sa.Uuid(), nullable=False),
    sa.Column('note_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['doctor.doctor_id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['clinical_note.note_id'], ),
    sa.PrimaryKeyConstraint('addendum_id')
    )
    op.create_table('note_event',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('note_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('content_snapshot', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['app_user.user_id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['clinical_note.note_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note_event')
    op.drop_table('note_addendum')
    op.drop_table('clinical_note')
    # ### end Alembic commands ###
