"""opinie per wizyta + lista oczekujacych

Revision ID: d09bd80266aa
Revises: 5200a7fe7f69
Create Date: 2026-06-10 19:39:37.979904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd09bd80266aa'
down_revision: Union[str, None] = '5200a7fe7f69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waiting_list',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('specialization', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('entry_id')
    )
    op.add_column('review', sa.Column('appointment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'review', 'appointment', ['appointment_id'], ['appointment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_column('review', 'appointment_id')
    op.drop_table('waiting_list')
    # ### end Alembic commands ###
