"""doctor: wiele specjalizacji (doctor_specialization)

Revision ID: e13168fbde53
Revises: 0a36b5ad5c7e
Create Date: 2026-06-15 21:11:07.777507

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e13168fbde53'
down_revision: Union[str, None] = '0a36b5ad5c7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_specialization',
    sa.Column('doctor_specialization_id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.doctor_id'], ),
    sa.PrimaryKeyConstraint('doctor_specialization_id'),
    sa.UniqueConstraint('doctor_id', 'name', name='uq_doctor_specialization')
    )
    # przeniesienie istniejących pojedynczych specjalizacji do nowej tabeli
    bind = op.get_bind()
    rows = bind.execute(sa.text(
        "SELECT doctor_id, specialization FROM doctor "
        "WHERE specialization IS NOT NULL AND specialization <> ''")).fetchall()
    for doctor_id, spec in rows:
        bind.execute(
            sa.text("INSERT INTO doctor_specialization (doctor_specialization_id, doctor_id, name) "
                    "VALUES (:id, :did, :name)"),
            {"id": uuid.uuid4(), "did": doctor_id, "name": spec})
    op.drop_column('doctor', 'specialization')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('specialization', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # powrót: pierwsza (alfabetycznie) specjalizacja z powrotem do skalarnego pola
    bind = op.get_bind()
    rows = bind.execute(sa.text(
        "SELECT DISTINCT ON (doctor_id) doctor_id, name FROM doctor_specialization "
        "ORDER BY doctor_id, name")).fetchall()
    for did, name in rows:
        bind.execute(sa.text("UPDATE doctor SET specialization = :name WHERE doctor_id = :did"),
                     {"name": name, "did": did})
    op.drop_table('doctor_specialization')
    # ### end Alembic commands ###
