"""clinic: reminder_mode (NONE/REMINDER/CONFIRM)

Revision ID: f055fc83c372
Revises: 4b0f1a7bf3a1
Create Date: 2026-06-16 00:32:23.570778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f055fc83c372'
down_revision: Union[str, None] = '4b0f1a7bf3a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinic', sa.Column('reminder_mode', sa.String(length=10), server_default='REMINDER', nullable=False))
    # backfill z dotychczasowej flagi: wymagane potwierdzenie → CONFIRM
    op.execute("UPDATE clinic SET reminder_mode = 'CONFIRM' WHERE confirmation_required = true")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinic', 'reminder_mode')
    # ### end Alembic commands ###
